<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20190412051321 extends AbstractMigration
{
    public function getDescription() : string
    {
        return '';
    }

    public function up(Schema $schema) : void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE production CHANGE capacity capacity INT DEFAULT NULL, CHANGE production production INT DEFAULT NULL, CHANGE inventory inventory INT DEFAULT NULL');

        $this->addSql("INSERT INTO region (id, name)
                            VALUES
                            ('1', 'Africa'),
                            ('2', 'Asia'),
                            ('3', 'CIS'),
                            ('4', 'EU28'),
                            ('5', 'Middle East'),
                            ('6', 'North America'),
                            ('7', 'Oceania'),
                            ('8', 'Other Europe'),
                            ('9', 'South America');");
        $this->addSql("INSERT INTO country (id, region_id, name)
                            VALUES
                            ('1', '1', 'Algeria'),
                            ('2', '1', 'Angola'),
                            ('3', '1', 'Benin'),
                            ('4', '1', 'Botswana'),
                            ('5', '1', 'Burkina Faso'),
                            ('6', '1', 'Cameroon'),
                            ('7', '1', 'Cape Verde'),
                            ('8', '1', 'Central African Republic'),
                            ('9', '1', 'Chad'),
                            ('10', '1', 'Congo'),
                            ('11', '1', 'Djibouti'),
                            ('12', '1', 'Egypt'),
                            ('13', '1', 'Equatorial Guinea'),
                            ('14', '1', 'Eritrea'),
                            ('15', '1', 'Ethiopia'),
                            ('16', '1', 'Gabon'),
                            ('17', '1', 'Ghana'),
                            ('18', '1', 'Guinea'),
                            ('19', '1', 'Ivory Coast'),
                            ('20', '1', 'Kenya'),
                            ('21', '1', 'Lesotho'),
                            ('22', '1', 'Liberia'),
                            ('23', '1', 'Libya'),
                            ('24', '1', 'Madagascar'),
                            ('25', '1', 'Malawi'),
                            ('26', '1', 'Maldives'),
                            ('27', '1', 'Mali'),
                            ('28', '1', 'Mauritania'),
                            ('29', '1', 'Mauritius'),
                            ('30', '1', 'Morocco'),
                            ('31', '1', 'Mozambique'),
                            ('32', '1', 'Namibia'),
                            ('33', '1', 'New Caledonia'),
                            ('34', '1', 'Niger'),
                            ('35', '1', 'Nigeria'),
                            ('36', '1', 'Reunion'),
                            ('37', '1', 'Rwanda'),
                            ('38', '1', 'Senegal'),
                            ('39', '1', 'Seychelles'),
                            ('40', '1', 'Sierra Leone'),
                            ('41', '1', 'Somalia'),
                            ('42', '1', 'South Africa'),
                            ('43', '1', 'Sudan'),
                            ('44', '1', 'Swaziland'),
                            ('45', '1', 'Tanzania'),
                            ('46', '1', 'Togo'),
                            ('47', '1', 'Tunisia'),
                            ('48', '1', 'Uganda'),
                            ('49', '1', 'Zambia'),
                            ('50', '1', 'Zimbabwe'),
                            ('51', '1', 'Zaire'),
                            ('52', '2', 'Bangladesh'),
                            ('53', '2', 'Bhutan'),
                            ('54', '2', 'Brunei'),
                            ('55', '2', 'Burundi'),
                            ('56', '2', 'Cambodia'),
                            ('57', '2', 'China'),
                            ('58', '2', 'Hong Kong'),
                            ('59', '2', 'India'),
                            ('60', '2', 'Indonesia'),
                            ('61', '2', 'Japan'),
                            ('62', '2', 'Thebones'),
                            ('63', '2', 'Malaysia'),
                            ('64', '2', 'Marshall Islands'),
                            ('65', '2', 'Mongolia'),
                            ('66', '2', 'Myanmar'),
                            ('67', '2', 'Nauru'),
                            ('68', '2', 'Nepal'),
                            ('69', '2', 'North Korea'),
                            ('70', '2', 'Pakistan'),
                            ('71', '2', 'Philippines'),
                            ('72', '2', 'Singapore'),
                            ('73', '2', 'South Korea'),
                            ('74', '2', 'Sri Lanka'),
                            ('75', '2', 'Taiwan'),
                            ('76', '2', 'Thailand'),
                            ('77', '2', 'Tonga'),
                            ('78', '2', 'Vietnam'),
                            ('79', '3', 'Armenia'),
                            ('80', '3', 'Azerbaijan'),
                            ('81', '3', 'Belarus'),
                            ('82', '3', 'Georgia'),
                            ('83', '3', 'Kazakhstan'),
                            ('84', '3', 'Moldova'),
                            ('85', '3', 'Russia'),
                            ('86', '3', 'Ukraine'),
                            ('87', '3', 'Uzbekistan'),
                            ('88', '4', 'Austria'),
                            ('89', '4', 'Belgium'),
                            ('90', '4', 'Bulgaria'),
                            ('91', '4', 'Croatia'),
                            ('92', '4', 'Cyprus'),
                            ('93', '4', 'Czech Republic'),
                            ('94', '4', 'Denmark'),
                            ('95', '4', 'Estonia'),
                            ('96', '4', 'Finland'),
                            ('97', '4', 'France'),
                            ('98', '4', 'Germany'),
                            ('99', '4', 'Greece'),
                            ('100', '4', 'Hungary'),
                            ('101', '4', 'Ireland'),
                            ('102', '4', 'Italy'),
                            ('103', '4', 'Latvia'),
                            ('104', '4', 'Lithuania'),
                            ('105', '4', 'Luxembourg'),
                            ('106', '4', 'Malta'),
                            ('107', '4', 'Netherlands'),
                            ('108', '4', 'Poland'),
                            ('109', '4', 'Portugal'),
                            ('110', '4', 'Romania'),
                            ('111', '4', 'Slovakia'),
                            ('112', '4', 'Slovenia'),
                            ('113', '4', 'Spain'),
                            ('114', '4', 'Sweden'),
                            ('115', '4', 'UK'),
                            ('116', '5', 'Afghanistan'),
                            ('117', '5', 'Bahrain'),
                            ('118', '5', 'Iran'),
                            ('119', '5', 'Iraq'),
                            ('120', '5', 'Israel'),
                            ('121', '5', 'Jordan'),
                            ('122', '5', 'Kuwait'),
                            ('123', '5', 'Kyrgyzstan'),
                            ('124', '5', 'Lebanon'),
                            ('125', '5', 'Oman'),
                            ('126', '5', 'Qatar'),
                            ('127', '5', 'Saudi Arabia'),
                            ('128', '5', 'Syria'),
                            ('129', '5', 'Tajikistan'),
                            ('130', '5', 'Turkmenistan'),
                            ('131', '5', 'UAE'),
                            ('132', '5', 'Yemen'),
                            ('133', '6', 'American Samoa'),
                            ('134', '6', 'Antigua & Barbuda'),
                            ('135', '6', 'Aruba'),
                            ('136', '6', 'Bahamas'),
                            ('137', '6', 'Barbados'),
                            ('138', '6', 'Belize'),
                            ('139', '6', 'Canada'),
                            ('140', '6', 'Cuba'),
                            ('141', '6', 'Dominican Republic'),
                            ('142', '6', 'El Salvador'),
                            ('143', '6', 'Guam'),
                            ('144', '6', 'Guatemala'),
                            ('145', '6', 'Haiti'),
                            ('146', '6', 'Jamaica'),
                            ('147', '6', 'Mexico'),
                            ('148', '6', 'Panama'),
                            ('149', '6', 'Puerto Rico'),
                            ('150', '6', 'Trinidad and Tobago'),
                            ('151', '6', 'USA'),
                            ('152', '7', 'Australia'),
                            ('153', '7', 'Fiji'),
                            ('154', '7', 'French Polynesia'),
                            ('155', '7', 'Micronesia'),
                            ('156', '7', 'New Zealand'),
                            ('157', '7', 'Niue'),
                            ('158', '7', 'Papua New Guinea'),
                            ('159', '7', 'Saint Vincent and the Grenadines'),
                            ('160', '7', 'Samoa ( Western Samoa)'),
                            ('161', '7', 'Solomon Islands'),
                            ('162', '7', 'Vanuatu'),
                            ('163', '8', 'Albania'),
                            ('164', '8', 'Bosnia'),
                            ('165', '8', 'Faroe Islands'),
                            ('166', '8', 'Gibraltar'),
                            ('167', '8', 'Kosovo'),
                            ('168', '8', 'Macedonia'),
                            ('169', '8', 'Montenegro'),
                            ('170', '8', 'Norway'),
                            ('171', '8', 'Serbia and Montenegro'),
                            ('172', '8', 'Switzerland'),
                            ('173', '8', 'Turkey'),
                            ('174', '8', 'Iceland'),
                            ('175', '9', 'Argentina'),
                            ('176', '9', 'Bolivia'),
                            ('177', '9', 'Brazil'),
                            ('178', '9', 'Chile'),
                            ('179', '9', 'Colombia'),
                            ('180', '9', 'Costa Rica'),
                            ('181', '9', 'Curacao'),
                            ('182', '9', 'Ecuador'),
                            ('183', '9', 'Guyana'),
                            ('184', '9', 'Honduras'),
                            ('185', '9', 'Nicaragua'),
                            ('186', '9', 'Paraguay'),
                            ('187', '9', 'Peru'),
                            ('188', '9', 'Suriname'),
                            ('189', '9', 'Uruguay'),
                            ('190', '9', 'Venezuela'),
                            ('191', '8', 'Other E.U.');");
        $this->addSql("INSERT INTO commodityGroup (id, name)
                            VALUES
                            ('1', 'Mn alloy'),
                            ('2', 'Mn ore (wet)'),
                            ('3', 'Mn ore (content)'),
                            ('4', 'Mn metal'),
                            ('5', 'Mn dioxide'),
                            ('6', 'Mn chemical'),
                            ('7', 'Steel');");
        $this->addSql("INSERT INTO commodity (id, commodity_group_id, name)
                            VALUES
                            ('1', '1', 'Silico-manganese (SiMn)'),
                            ('2', '1', 'Refined ferro-manganese (Ref FeMn)'),
                            ('3', '1', 'High-carbon ferro-manganese (HC FeMn)'),
                            ('4', '2', 'Mn Ore Wet (High Grade) (≥ 44%)'),
                            ('5', '3', 'Mn Ore Content (High Grade) (≥ 44%)'),
                            ('6', '2', 'Mn Ore Wet (Mid Grade) (> 30% and < 44%)'),
                            ('7', '3', 'Mn Ore Content (Mid Grade) (> 30% and < 44%)'),
                            ('8', '2', 'Mn Ore Wet (Low Grade) (≤ 30%)'),
                            ('9', '3', 'Mn Ore Content (Low Grade) (≤ 30%)'),
                            ('10', '4', 'Aluminothermic Mn metal (AMM)'),
                            ('11', '4', 'Electrolytic Mn metal (EMM)'),
                            ('12', '5', 'Chemical Mn dioxide (CMD)'),
                            ('13', '5', 'Electrolytic Mn dioxide (EMD)'),
                            ('14', '6', 'Mn sulphate (MnSO4)'),
                            ('15', '6', 'Trimanganese tetraoxide (Mn3O4)'),
                            ('16', '7', 'Carbon steel'),
                            ('17', '7', 'Stainless steel');");
    }

    public function down(Schema $schema) : void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE production CHANGE capacity capacity INT NOT NULL, CHANGE production production INT NOT NULL, CHANGE inventory inventory INT NOT NULL');
    }
}
